styles = {'img': 512, 'text': 0, 'canny': 0, 'seg': 0}
style_weights = {'img': 1, 'text': 1, 'canny': 1, 'seg': 1}
modality_dims = {'img': 512, 'text': 512, 'canny': 256, 'seg': 256}
indices = {'img': 0, 'text': 1, 'canny': 2, 'seg': 3}
modalities = ['img', 'text', 'canny', 'seg']
LABELS = ['5_o_Clock_Shadow', 'Arched_Eyebrows', 'Attractive',
          'Bags_Under_Eyes', 'Bald', 'Bangs', 'Big_Lips', 'Big_Nose', 'Black_Hair',
          'Blond_Hair', 'Blurry', 'Brown_Hair', 'Bushy_Eyebrows',
          'Chubby', 'Double_Chin', 'Eyeglasses', 'Goatee',
          'Gray_Hair', 'Heavy_Makeup', 'High_Cheekbones', 'Male',
          'Mouth_Slightly_Open', 'Mustache',
          'Narrow_Eyes', 'No_Beard', 'Oval_Face', 'Pale_Skin',
          'Pointy_Nose', 'Receding_Hairline', 'Rosy_Cheeks',
          'Sideburns', 'Smiling', 'Straight_Hair', 'Wavy_Hair',
          'Wearing_Earrings', 'Wearing_Hat',
          'Wearing_Lipstick', 'Wearing_Necklace',
          'Wearing_Necktie', 'Young']
TEXT_LABELS = LABELS
# ! filtering out classifier's AP > 0.6
IMG_LABELS = ['5_o_Clock_Shadow',
 'Arched_Eyebrows',
 'Attractive',
 'Bald',
 'Bangs',
 'Big_Nose',
 'Black_Hair',
 'Blond_Hair',
 'Brown_Hair',
 'Bushy_Eyebrows',
 'Eyeglasses',
 'Goatee',
 'Gray_Hair',
 'Heavy_Makeup',
 'High_Cheekbones',
 'Male',
 'Mouth_Slightly_Open',
 'No_Beard',
 'Rosy_Cheeks',
 'Sideburns',
 'Smiling',
 'Wavy_Hair',
 'Wearing_Earrings',
 'Wearing_Hat',
 'Wearing_Lipstick',
 'Young']

CANNY_LABELS = ['Arched_Eyebrows',
 'Attractive',
 'Bangs',
 'Big_Nose',
 'Black_Hair',
 'Blond_Hair',
 'Bushy_Eyebrows',
 'Eyeglasses',
 'Goatee',
 'Gray_Hair',
 'Heavy_Makeup',
 'High_Cheekbones',
 'Male',
 'Mouth_Slightly_Open',
 'No_Beard',
 'Smiling',
 'Wavy_Hair',
 'Wearing_Earrings',
 'Wearing_Hat',
 'Wearing_Lipstick',
 'Young']

SEMANTIC_LABELS = ['Arched_Eyebrows',
 'Attractive',
 'Bald',
 'Bangs',
 'Big_Nose',
 'Bushy_Eyebrows',
 'Eyeglasses',
 'Heavy_Makeup',
 'High_Cheekbones',
 'Male',
 'Mouth_Slightly_Open',
 'No_Beard',
 'Smiling',
 'Wavy_Hair',
 'Wearing_Earrings',
 'Wearing_Hat',
 'Wearing_Lipstick',
 'Young']